export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO'

//TYPES FORMULARIO
export const FORMULARIO_PROYECTO = 'FORMULARIO_PROYECTO'
export const OBTENER_PROYECTOS = 'OBTENER_PROYECTOS'
export const AGREGAR_PROYECTO = 'AGREGAR_PROYECTO'
export const PROYECTO_ACTUAL = 'PROYECTO_ACTUAL'
export const ELIMINAR_PROYECTO = 'ELIMINAR_PROYECTO'

//TYPES TAREAS
export const TAREAS_PROYECTO = 'TAREAS_PROYECTO'
export const AGREGAR_TAREA = 'AGREGAR_TAREA'

